-- Script para inserir os novos passeios na tabela passeios
-- Execute este script no Supabase SQL Editor

INSERT INTO passeios (
  nome,
  subtitulo,
  imagem_url,
  duracion,
  local_saida,
  horario_saida,
  inclui_transporte,
  guia_turistico,
  descricao,
  preco_adulto,
  preco_crianca_0_3,
  preco_crianca_4_5,
  preco_crianca_6_10,
  ativo
) VALUES 
(
  'Bombinhas',
  'Trilha, Río y Playa Salvaje',
  '/images/paseos/Bombinhas/1.jpeg',
  '8 horas',
  'Florianópolis',
  '08:00',
  true,
  true,
  'Explore as praias paradisíacas de Bombinhas com trilhas ecológicas, mergulho livre e muito mais.',
  89.90,
  0,
  45.00,
  89.90,
  true
),
(
  'City Tour – Florianópolis',
  'Historia y Cultura Local',
  '/images/paseos/City Tour – Florianópolis/1.jpg',
  '6 horas',
  'Florianópolis',
  '09:00',
  true,
  true,
  'Conheça os principais pontos turísticos de Florianópolis com guia especializado.',
  79.90,
  0,
  40.00,
  79.90,
  true
),
(
  'Guarda do Embaú',
  'Trilha, Río y Playa Salvaje',
  '/images/paseos/Guarda do Embaú/1.jpeg',
  '7 horas',
  'Florianópolis',
  '08:30',
  true,
  true,
  'Aventure-se na praia selvagem de Guarda do Embaú com trilhas e natureza preservada.',
  69.90,
  0,
  35.00,
  69.90,
  true
),
(
  'Mergulho',
  'Aventura Submarina',
  '/images/paseos/Mergulho/1.jpeg',
  '5 horas',
  'Florianópolis',
  '07:00',
  true,
  true,
  'Viva a experiência do mergulho com cilindro nas águas cristalinas de Florianópolis.',
  129.90,
  0,
  65.00,
  129.90,
  true
),
(
  'Aqua Show Park',
  'Diversión Acuática en Familia',
  '/images/paseos/Aqua Show Park/1.jpg',
  '10 horas',
  'Florianópolis',
  '08:00',
  true,
  true,
  'Diversão garantida para toda a família no maior parque aquático da região.',
  99.90,
  0,
  50.00,
  99.90,
  true
); 