import type { Disponibilidade, CidadeSaida } from './supabase'

export const FALLBACK_DISPONIBILIDADES: Disponibilidade[] = [
  {
    id: 1,
    destino: 'Canasvieiras',
    data_saida: '2025-11-23',
    transporte: 'Bus',
    hotel: 'Residencial Terrazas',
    quarto_tipo: 'Habitación Cuádruple',
    capacidade: 4,
    preco_adulto: 490,
    preco_crianca_0_3: 50,
    preco_crianca_4_5: 350,
    preco_crianca_6_mais: 490,
    noites_hotel: 7,
    dias_viagem: 8,
    dias_totais: 8,
    link_imagem: '/placeholder.jpg',
    slug: 'canasvieiras-residencial-terrazas',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 2,
    destino: 'Canasvieiras',
    data_saida: '2025-11-30',
    transporte: 'Bus',
    hotel: 'Residencial Leonidas',
    quarto_tipo: 'Habitación Cuádruple',
    capacidade: 4,
    preco_adulto: 490,
    preco_crianca_0_3: 50,
    preco_crianca_4_5: 350,
    preco_crianca_6_mais: 490,
    noites_hotel: 7,
    dias_viagem: 8,
    dias_totais: 8,
    link_imagem: '/placeholder.jpg',
    slug: 'canasvieiras-residencial-leonidas',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 3,
    destino: 'Canasvieiras',
    data_saida: '2025-12-07',
    transporte: 'Bus',
    hotel: 'Hotel Fenix',
    quarto_tipo: 'Habitación Doble',
    capacidade: 6,
    preco_adulto: 490,
    preco_crianca_0_3: 50,
    preco_crianca_4_5: 350,
    preco_crianca_6_mais: 490,
    noites_hotel: 5,
    dias_viagem: 6,
    dias_totais: 6,
    link_imagem: '/placeholder.jpg',
    slug: 'canasvieiras-hotel-fenix',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 4,
    destino: 'Canasvieiras',
    data_saida: '2025-11-23',
    transporte: 'Aéreo',
    hotel: 'Resort Premium',
    quarto_tipo: 'Habitación Suite',
    capacidade: 6,
    preco_adulto: 490,
    preco_crianca_0_3: 50,
    preco_crianca_4_5: 350,
    preco_crianca_6_mais: 490,
    noites_hotel: 7,
    dias_viagem: 8,
    dias_totais: 8,
    link_imagem: '/placeholder.jpg',
    slug: 'canasvieiras-resort-premium',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 5,
    destino: 'Canasvieiras',
    data_saida: '2025-12-14',
    transporte: 'Bus',
    hotel: 'Hotel Costa Verde',
    quarto_tipo: 'Habitación Triple',
    capacidade: 5,
    preco_adulto: 490,
    preco_crianca_0_3: 50,
    preco_crianca_4_5: 350,
    preco_crianca_6_mais: 490,
    noites_hotel: 7,
    dias_viagem: 8,
    dias_totais: 8,
    link_imagem: '/placeholder.jpg',
    slug: 'canasvieiras-hotel-costa-verde',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 6,
    destino: 'Florianópolis',
    data_saida: '2025-11-23',
    transporte: 'Aéreo',
    hotel: 'Pousada Sol e Mar',
    quarto_tipo: 'Habitación Familiar',
    capacidade: 6,
    preco_adulto: 490,
    preco_crianca_0_3: 50,
    preco_crianca_4_5: 350,
    preco_crianca_6_mais: 490,
    noites_hotel: 5,
    dias_viagem: 6,
    dias_totais: 6,
    link_imagem: '/placeholder.jpg',
    slug: 'florianopolis-pousada-sol-e-mar',
    created_at: '2025-01-01T00:00:00Z',
  },
  {
    id: 7,
    destino: 'Bombinhas',
    data_saida: '2026-01-04',
    transporte: 'Bus',
    hotel: 'BOMBINHAS PALACE HOTEL',
    quarto_tipo: 'Habitación Doble',
    capacidade: 4,
    preco_adulto: 490,
    preco_crianca_0_3: 50,
    preco_crianca_4_5: 350,
    preco_crianca_6_mais: 490,
    noites_hotel: 7,
    dias_viagem: 8,
    dias_totais: 8,
    link_imagem: '/placeholder.jpg',
    slug: 'bombinhas-palace-hotel',
    created_at: '2025-01-01T00:00:00Z',
  },
]

export const FALLBACK_CIDADES: CidadeSaida[] = [
  { id: 1, transporte: 'Bus', cidade: 'Buenos Aires', provincia: 'Buenos Aires', pais: 'Argentina' },
  { id: 2, transporte: 'Bus', cidade: 'São Paulo', provincia: 'São Paulo', pais: 'Brasil' },
  { id: 3, transporte: 'Aéreo', cidade: 'Rio de Janeiro', provincia: 'Rio de Janeiro', pais: 'Brasil' },
]

