-- Core schema for Nice Trip admin features
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE OR REPLACE FUNCTION public.handle_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = timezone('utc', now());
  RETURN NEW;
END;
$$;

CREATE TABLE IF NOT EXISTS public.admin_users (
  user_id uuid PRIMARY KEY REFERENCES auth.users (id) ON DELETE CASCADE,
  role text DEFAULT 'admin',
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE TABLE IF NOT EXISTS public.discount_rules (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  transport_type text,
  destinations text[],
  package_slugs text[],
  hotel_names text[],
  age_min integer,
  age_max integer,
  amount numeric NOT NULL,
  amount_currency text NOT NULL DEFAULT 'USD',
  amount_type text NOT NULL CHECK (amount_type IN ('fixed','percent')),
  valid_from date,
  valid_to date,
  is_active boolean NOT NULL DEFAULT true,
  created_by uuid REFERENCES auth.users (id),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS discount_rules_active_idx
  ON public.discount_rules (is_active, valid_from, valid_to);

DROP TRIGGER IF EXISTS set_discount_rules_updated_at ON public.discount_rules;
CREATE TRIGGER set_discount_rules_updated_at
BEFORE UPDATE ON public.discount_rules
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

CREATE TABLE IF NOT EXISTS public.disponibilidades (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  destino text NOT NULL,
  data_saida date NOT NULL,
  transporte text NOT NULL,
  hotel text NOT NULL,
  quarto_tipo text,
  slug text,
  slug_hospedagem text,
  slug_pacote text,
  slug_pacote_principal text,
  hospedagem_id uuid,
  capacidade integer,
  preco_adulto numeric,
  preco_crianca_0_3 numeric,
  preco_crianca_4_5 numeric,
  preco_crianca_6_mais numeric,
  preco_adulto_aereo numeric,
  preco_crianca_0_2_aereo numeric,
  preco_crianca_2_5_aereo numeric,
  preco_crianca_6_mais_aereo numeric,
  taxa_aereo_por_pessoa numeric DEFAULT 200,
  noites_hotel integer,
  dias_viagem integer,
  dias_totais integer,
  link_imagem text,
  cidade_saida text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now()),
  updated_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS disponibilidades_destino_data_idx
  ON public.disponibilidades (destino, data_saida);

CREATE INDEX IF NOT EXISTS disponibilidades_transporte_idx
  ON public.disponibilidades (transporte);

DROP TRIGGER IF EXISTS set_disponibilidades_updated_at ON public.disponibilidades;
CREATE TRIGGER set_disponibilidades_updated_at
BEFORE UPDATE ON public.disponibilidades
FOR EACH ROW
EXECUTE FUNCTION public.handle_updated_at();

CREATE TABLE IF NOT EXISTS public.search_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  filters jsonb NOT NULL,
  result_count integer,
  user_agent text,
  ip_hash text,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS search_events_created_at_idx
  ON public.search_events (created_at DESC);

CREATE TABLE IF NOT EXISTS public.conversion_events (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  context jsonb,
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS conversion_events_created_at_idx
  ON public.conversion_events (created_at DESC);

CREATE TABLE IF NOT EXISTS public.audit_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  entity text NOT NULL,
  entity_id text,
  action text NOT NULL,
  payload jsonb,
  performed_by uuid REFERENCES auth.users (id),
  created_at timestamptz NOT NULL DEFAULT timezone('utc', now())
);

CREATE INDEX IF NOT EXISTS audit_logs_entity_idx
  ON public.audit_logs (entity, created_at DESC);

CREATE INDEX IF NOT EXISTS audit_logs_performed_by_idx
  ON public.audit_logs (performed_by, created_at DESC);

